[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "0xProto"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "0xProto"

[font.normal]
family = "0xProto"
style = "Medium"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
opacity = 0.4
